export default {
	credits: ["RobertR11"],
	global: {
		name: "Faithful",
		login: "Anmelden",
		logout: "Abmelden",
		ends_success: "Erfolgreich abgeschlossen",
		loading: "Wird geladen, bitte warten…",
		no_results: "Es wurden keine Ergebnisse gefunden",
		nyi: "Noch nicht implementiert",
		invalid_url: "Diese URL ist ungültig",
		navbar: {
			labels: {
				sidebar: "Seitenleiste umschalten",
				theme: "Erscheinungsbild-Dropdown umschalten",
				translations: "Übersetzungs-Dropdown umschalten",
				user: "Angemeldet als %s",
			},
			translations: {
				title: "Übersetzungen",
				crowdin: "Übersetzen helfen",
			},
			profile: {
				view: "Dein Profil",
				main_site: "Faithful Webseite",
				manage: "Konten verwalten",
				copy: "Benutzer-ID kopieren",
				copied: "Benutzer-ID in Zwischenablage kopiert",
			},
		},
		footer: {
			credits: "Diese Website wurde mit dem %Vuetify% Komponenten-Framework erstellt.",
			source: "Sehe die Quelle %hier%!",
			copyright: "© %d Faithful Resource Pack",
		},
		themes: {
			notification: "System-Erscheinungsbild auf %s geändert",
			dark_sidebar: "Dunkle Seitenleiste",
			title: "Erscheinungsbild",
			options: {
				light: "Hell",
				dark: "Dunkel",
				system: "Systemstandard",
			},
		},
		btn: {
			add: "Hinzufügen",
			add_download: "Download hinzufügen",
			submit: "Senden",
			submit_for_review: "Zur Überprüfung senden",
			submit_and_approve: "Senden und genehmigen",
			cancel: "Abbrechen",
			close: "Schließen",
			save: "Speichern",
			edit: "Bearbeiten",
			delete: "Löschen",
			ok: "OK",
			yes: "Ja",
			deny: "Ablehnen",
			approve: "Genehmigen",
			archive: "Archivieren",
			load_more: "Mehr laden",
			reset: "Formular zurücksetzen",
			confirm: "Bestätigen",
			publish: "Veröffentlichen",
			save_draft: "Als Entwurf speichern",
		},
		tabs: {
			general: {
				title: "Allgemein",
				subtabs: {
					dashboard: "Dashboard",
					profile: "Profil",
					gallery: "Galerie",
				},
			},
			addons: {
				title: "Add-ons",
				subtabs: {
					submissions: "Einsendungen",
					upload: "Hochladen",
					review: "Überprüfen",
				},
			},
			posts: {
				title: "Beiträge",
				subtabs: {
					list: "Liste",
					create: "Erstellen",
				},
			},
			database: {
				title: "Datenbank",
				subtabs: {
					contributions: "Beiträge",
					users: "Benutzer",
					textures: "Texturen",
					versions: "Versionen",
					packs: "Packs",
					settings: "Einstellungen",
				},
			},
		},
		json_editor: {
			import_data: "JSON-Daten importieren",
			parse_json: "JSON in Daten konvertieren",
		},
		datepicker: {
			year: "Jahr",
			month: "Monat",
			day: "Tag",
		},
		tabbed_text_field: {
			write: "Schreiben",
			preview: "Vorschau",
			empty: "Keine Vorschau verfügbar",
		},
		drop_zone: {
			standby_singular: "Datei ablegen oder zum Auswählen klicken",
			standby_plural: "Dateien ablegen oder zum Auswählen klicken",
			dragging_singular: "Loslassen, um Datei hochzuladen",
			dragging_plural: "Loslassen, um Dateien hochzuladen",
		},
		account_manager: {
			title: "Konten Manager",
			active_account: "Aktives Konto",
			add_account: "Neues Konto hinzufügen",
			avatar_alt_text: "%s's Profilbild",
		},
	},
	missing_page: {
		title: "Bist du im End verloren?",
		description: "Leider existiert die aufgerufene Seite nicht!",
		main_page:
			"Überprüfe die Rechtschreibung oder gehe zur %Hauptseite% um zu finden, was du gesucht hast.",
	},
	dashboard: {
		welcome_user: "Willkommen, %USER%!",
		welcome: "Willkommen!",
		totals: {
			authors: "Autoren",
			contributions: "Beiträge",
			last_day: "Beiträge in den letzten 48 Stunden",
			last_week: "Beiträge letzte Woche",
			last_month: "Beiträge letzten Monat",
		},
		titles: {
			profile: "Dein Profil",
			textures: "Texturen",
			addons: "Add-ons",
			contribution_stats: "Beiträge",
			contribution_activity: "Beitragsaktivitäten",
		},
		profile: {
			login_notice: "Melde dich an, um auf weitere Funktionen zuzugreifen!",
			login_button: "Mit Discord anmelden",
		},
		addons: {
			submissions: "Einsendungen",
			upload: "Hochladen",
		},
		textures: {
			total: "Texturen",
			versions: "Versionen",
		},
		locale: {
			on: "An",
			less: "Weniger",
			more: "Mehr",
		},
	},
	profile: {
		title: "Profil anpassen",
		public_profile: "Öffentliches Profil ansehen",
		general: {
			title: "Allgemein",
			username: {
				label: "Benutzername",
				hint: "Dein Benutzername wird auf der Website angezeigt und für Beiträge, Add-ons usw. verwendet",
				rules: {
					min: "Benutzername muss länger als %d Zeichen sein",
					max: "Benutzername muss kleiner als %d Zeichen sein",
				},
			},
			uuid: {
				label: "Minecraft-Profil UUID",
				hint: "Dein Skin wird auf deiner Profilseite und Add-ons angezeigt",
				skin_alt_text: "Minecraft Skin",
				rules: {
					length: "UUID muss genau 36 Zeichen lang sein",
				},
			},
			bio: {
				label: "Biografie",
				placeholder: "Biografie",
				hint: "Du kannst Markdown-Formatierung verwenden, um deine Beschreibung zu stylen!",
				rules: {
					length: "Bio muss kleiner als %d Zeichen sein",
				},
			},
			anonymous: {
				label: "Anonym",
				hint: "Deaktiviert die Profilseite und versteckt den Benutzernamen und Minecraft Skin in der Textur-Galerie. Der Benutzername wird in Textur Einsendungen zwecks Urhebernennung weiterhin zugänglich sein, wird aber nirgendwo anders erscheinen.",
			},
		},
		social: {
			title: "Social media",
			add: "Social Media hinzufügen",
			type: {
				label: "Social-Typ",
				rules: {
					exists: "Social-Typ ist erforderlich",
					valid: "Social-Typ muss gültig sein",
				},
			},
			link: {
				label: "Link zum sozialen Profil",
				placeholder: "https://www.beispiel.de/",
				rules: {
					valid: "Die URL muss gültig sein.",
				},
			},
		},
		save_changes: "Änderungen speichern",
		delete: {
			title: "Konto löschen",
			btn: "Konto löschen",
			description: "Bist du dir sicher, dass du deinen Account löschen willst?",
			warning: "Dieser Vorgang kann nicht rückgängig gemacht werden!",
			addons: {
				title_singular: "Dies wirkt sich auf das %d Add-on aus",
				title_plural: "Dies wirkt sich auf %d Add-ons aus",
				deleted: "Gelöscht",
				transferred: "Auf andere Autoren übertragen",
			},
		},
	},
	gallery: {
		title: "Galerie",
		max_items_per_row: "Max. Elemente pro Zeile",
		stretched_switcher: "Ansicht mit voller Breite",
		animated_switcher: "Animierte Texturen abspielen",
		share: "Textur teilen",
		to_top: "Zurück zum Seitenstart",
		share_link_copied_to_clipboard: "Freigabelink in Zwischenablage kopiert",
		authors_copied_to_clipboard: "Autoren der Textur in die Zwischenablage kopiert",
		loading_message: "Lade Galerieergebnisse…",
		error_message: {
			texture_not_done: "Diese Textur fehlt!",
			user_anonymous: "Anonym",
			user_not_found: "Unbekannter Benutzer",
			contribution_not_found: "Keine Beiträge in der Datenbank gefunden!",
			search_failed: "Suche fehlgeschlagen",
		},
		category: {
			search: "Suchen",
			tag: "Tag",
			mc_version: "Minecraft-Version",
			edition: "Edition",
			pack: "Pack",
		},
		sort: {
			name_asc: "Name (A → Z)",
			name_desc: "Name (Z → A)",
			id_asc: "Textur-ID (kleinste → größte)",
			id_desc: "Textur-ID (größte → kleinste)",
			contrib_desc: "Kürzlich beigetragen",
		},
		tooltip: {
			modded: "Modded-Textur",
			mojang: "Mojang Studios",
			ignored: "Ignorierte Textur",
		},
		all: "Alle",
		latest: "Aktuell",
		clear_cache: "Galerie-Cache leeren",
		result_stats_singular: "%COUNT% Textur in %SECONDS% Sekunden gefunden",
		result_stats_plural: "%COUNT% Texturen in %SECONDS% Sekunden gefunden",
		modal: {
			no_contributions: "Keine Beiträge gefunden",
			image_alt_text: "Textur %NAME% für Pack %PACK%",
			loading: "Lade Textur…",
			tabs: {
				information: "Informationen",
				authors: "Autoren",
				animation: "Animation",
			},
			info: {
				texture: "Textur",
				uses: "Verwendungen",
				paths: "Pfade",
			},
			animation: {
				texture_mcmeta: "MCMETA",
			},
			data: {
				contribution_id: "Beitrags-ID",
				date: "Datum",
				authors: "Autoren",
				id: "ID",
				name: "Name",
				tags: "Tags",
				use_id: "Verwendungs-ID",
				use_name: "Verwendungsname",
				edition: "Edition",
				texture_id: "Textur-ID",
				path_id: "Pfad-ID",
				resource_pack_path: "Resource Pack Pfad",
				mc_versions: "Minecraft Versionen",
			},
		},
	},
	addons: {
		titles: {
			submit: "Ein neues Add-on einsenden",
			edit: "Add-on bearbeiten",
			submissions: "Add-on Einsendungen",
			details: "Details",
		},
		remove: {
			title: "Löschung bestätigen",
			labels: {
				question: "Willst du %s löschen?",
				warning: "Du kannst diesen Vorgang nicht rückgängig machen.",
			},
		},
		general: {
			loading_addon: "Lade Add-on…",
			no_submissions: "Du hast keine eingesendeten Add-ons!",
			rules: "Bitte lese die Add-on Regeln vor dem Einsenden",
			title: "Allgemein",
			name: {
				label: "Add-on Name",
				hint: "Ein kürzerer Name ist bevorzugt",
				rules: {
					name_required: "Ein Name ist erforderlich.",
					name_too_big: "Add-on Name muss kleiner als %s Zeichen sein",
					name_too_small: "Add-on Name muss mindestens %s Zeichen lang sein",
					name_unavailable: "Dieser Name ist bereits vergeben!",
				},
			},
			slug: {
				label: "Add-on Slug",
				hint: "Das Ändern dieser Option wird alte Links kaputt machen!",
			},
			reason: {
				title: "Grund der Aktualisierung",
				text: "Bitte teile mit, was aktualisiert wurde, um die Überprüfung des Add-ons zu erleichtern!",
				required: "Ein Update-Grund ist erforderlich",
				bounds: "Updategrund muss zwischen %s und %s Zeichen lang sein",
			},
			authors: {
				label: "Autoren für das Add-on auswählen",
				hint: "Jeder Autor kann das Add-on ändern, sobald es eingesendet wurde! | Wenn du in der Liste niemanden finden kannst, der dort sein sollte, kontaktiere einen Administrator oder Entwickler",
			},
		},
		info: {
			title: "Informationen",
			description: {
				placeholder: "Add-on Beschreibung",
				hint: "Du kannst die Markdown-Formatierung verwenden, um deine Beschreibung zu verbessern!",
				rules: {
					description_required: "Die Beschreibung ist erforderlich",
					description_too_big: "Beschreibung muss kleiner als %s Zeichen sein",
					description_too_small: "Beschreibung muss mindestens %s Zeichen lang sein",
				},
			},
			embed_description: {
				label: "Embed-Beschreibung",
				hint: "Beschreibung beim Teilen des Add-ons auf sozialen Medien angezeigt",
				rules: {
					too_big: "Embed-Beschreibung muss kleiner als %s Zeichen sein",
				},
			},
		},
		images: {
			title: "Screenshots",
			header: {
				labels: {
					drop: "Klicken Sie, um zusätzliche Bilder auszuwählen",
					normal: "Header-Bild",
					replace: "Header-Bild ersetzen",
				},
				rules: {
					image_size:
						"Die Bild sollte weniger als %s KB groß sein! Benutze https://compressor.io/ es zu komprimieren.",
					image_ratio:
						"Falsches Seitenverhältnis: Das bereitgestellte Bild hat nicht das Seitenverhältnis 16:9.",
					image_required: "Ein Header-Bild ist erforderlich.",
					jpeg: "Bild muss ein komprimiertes JPEG sein",
					compress: "Bilder können mit https://compressor.io/ komprimiert werden",
				},
			},
			carousel: {
				labels: {
					drop: "Zusätzliche Bilder ablegen oder zum Auswählen klicken",
					normal: "Zusätzliche Bilder",
					replace: "Zusätzliche Bilder ersetzen",
				},
				rule: "Falsches Seitenverhältnis: Bilder ohne einem Seitenverhältnis von 16:9 wurden entfernt.",
			},
		},
		compatibility: {
			title: "Kompabilität",
			optifine: {
				label: "Benötigt OptiFine",
			},
			editions: {
				label: "Unterstützte Editionen",
			},
			packs: {
				label: "Unterstützte Packs",
			},
		},
		downloads: {
			title: "Downloads",
			name: {
				placeholder: "CurseForge, GitHub…",
				label: "Name",
				rules: {
					name_required: "Ein Name ist erforderlich.",
					name_cannot_be_empty: "Name kann nicht leer sein.",
				},
			},
			link: {
				placeholder: "https://www.beispiel.de/",
				label: "Link",
				rule: "Die URL muss gültig sein.",
			},
		},
		status: {
			approved: "Genehmigt",
			denied: "Abgelehnt",
			pending: "Ausstehend",
			archived: "Archiviert",
		},
	},
	review: {
		titles: {
			addons: "Add-ons überprüfen",
			pending: "Genehmigung ausstehend",
			denied: "Abgelehnt",
			approved: "Genehmigt",
			archived: "Archiviert",
		},
		deny_window: {
			title: "Add-on ablehnen",
			archive_title: "Add-on archivieren",
			label: "Schreibe einen Grund…",
			rule: "Ein beliebiger Grund kann angegeben werden",
		},
		labels: {
			pending: "Es gibt derzeit keine ausstehenden Add-ons!",
			denied: "Es gibt derzeit keine abgelehnten Add-ons!",
			archived: "Es gibt derzeit keine archivierten Add-ons!",
			approved: "Es gibt derzeit keine genehmigten Add-ons!",
			load_approved: "Genehmigte Add-ons laden",
		},
		addon: {
			titles: {
				last_updated: "Zuletzt aktualisiert %s",
				unknown_date: "Letzte Add-on-Aktualisierung unbekannt",
				author_singular: "Autor",
				author_plural: "Autoren",
				description: "Beschreibung",
				links: "Links",
				options: "Optionen",
			},
			labels: {
				link: "Link",
				optifine: "OptiFine",
				approved_by: "Genehmigt von %s",
				denied_by: "Abgelehnt von %s",
				reason: "Grund",
			},
		},
	},
	posts: {
		titles: {
			list: "Alle Posts",
			edit: "Post bearbeiten",
			new: "Neuen Post erstellen",
		},
		status: {
			published: "Veröffentlicht",
			draft: "Entwurf",
		},
		loading: "Lade Post…",
		general: {
			heading: "Allgemein",
			title: {
				label: "Post-Titel",
				placeholder: "Faithful Smart Fridge: Alpha 1",
			},
			permalink: {
				label: "Permalink",
				placeholder: "/faithfulsmartfridge/A1",
			},
			header_img: {
				label: "Kopfzeilenbild (optional)",
				hint: "Hinweis: Dies muss separat hochgeladen werden",
				placeholder: "https://database.faithfulpack.net/images/website/posts/fridge/A1.jpg",
			},
			date: {
				label: "Veröffentlichungsdatum",
			},
			discontinued: {
				label: "Nicht mehr unterstützt",
				hint: "Wenn aktiviert, wird der Post als nicht mehr unterstützt markiert",
			},
			description: {
				placeholder: "Post-Beschreibung",
				hint: "Du kannst die Markdown-Formatierung verwenden, um deine Beschreibung zu verbessern!",
			},
		},
		download: {
			heading: "Downloads",
			add_category: "Download-Kategorie hinzufügen",
			add_single_item: "Einzelen Download hinzufügen",
			category: "Download-Kategorie Name",
			name: "Download-Name",
			link: "Download Link",
			link_placeholder: "https://www.beispiel.de/",
		},
		changelog: {
			heading: "Änderungsprotokoll",
			add_category: "Änderungsprotokoll Kategorie hinzufügen",
			add_item: "Änderungsprotokoll Element hinzufügen",
			import_json: "JSON importieren",
			form_levels: {
				primary: "Hauptkategorie",
				secondary: "Unterkategorie",
				item_category: "Objektkategorie (Autoren)",
				item: "Objekt (Autoren)",
			},
		},
		changelog_generator: {
			heading: "Änderungsprotokoll generieren",
			date: "Datum seit letztem Änderungsprotokoll",
			pack: "Änderungsprotokoll Pack",
			copy: "In Zwischenablage kopieren",
			categorize: "Änderungsprotokoll automatisch nach Typ kategorisieren (experimentell)",
			categorize_warning: "Typkategorisierung kann ungenau sein, da Beiträge getrackt werden!",
			download: "Änderungsprotokoll herunterladen",
			warning: "Bitte überprüfe das Änderungsprotokoll vor dem importieren manuell!",
		},
	},
	database: {
		search: "Suchen",
		anonymous: "Anonym",
		nameless: "Namenlos",
		summary: "Zusammenfassung",
		confirm_deletion: "Löschung bestätigen",
		ask_deletion: "Willst du %s (%d) löschen?",
		contributions: {
			title: "Beiträge",
			contributors: "Mitwirkende",
			add_contributions: "Neuen Beitrag hinzufügen",
			pack_filter: "Nach Texture Pack filtern",
			user_filter: "Benutzer",
			texture_filter: "Texturen",
			select_user: "Benutzer auswählen",
			contribution_count_singular: "%d Beitrag",
			contribution_count_plural: "%d Beiträge",
			no_contributor_yet: "Noch keine Beiträge",
			contribution_result: "Beiträge",
			search_contributions: "Beiträge suchen",
			modal: {
				add_new_contribution: "Neuen Beitrag hinzufügen",
				clone_contribution: "Beitrag klonen",
				one_contributor: "Bitte wähle mindestens einen Mitwirkenden",
				pack: "Resource Pack",
				texture_id: "Textur-ID",
				texture_ids: "Textur-IDs",
				id_field_errors: {
					one_required: "Mindestens eine Textur-ID oder ein ID-Bereich sind erforderlich",
					incorrect_value: "Falsche Textur %value% ID oder ID-Bereich",
				},
			},
		},
		users: {
			title: "Benutzer",
			role_filter: "Mitwirkende/r-Typ auswählen",
			search_username: "Benutzernamen suchen",
			user_result: "Benutzerergebnisse",
			modal: {
				add_user: "Neuen Mitwirkenden hinzufügen",
				change_user: "Mitwirkende bearbeiten",
				id: "Discord-ID",
				username: "Benutzername",
				uuid: "Minecraft-Profil UUID",
				roles: "Art des Mitwirkenden",
				anonymous: "Anonym",
			},
		},
		textures: {
			title: "Texturen",
			add_texture: "Neue Textur hinzufügen",
			add_multiple: "Neue Texturen hinzufügen",
			change_texture: "Textur bearbeiten",
			texture_result: "Texturergebnisse",
			tag_filter: "Texturtyp auswählen",
			search_texture: "Texturname suchen",
			add_success: "Texturen erfolgreich hinzugefügt",
			delete_modal: {
				deleting_use_will_delete_paths: "Das Löschen einer Verwendung löscht auch alle Pfade",
				load_paths: "Betroffene Pfade laden",
			},
			modal: {
				title: "Textur",
				subtitle: "Verwendungen und Pfade",
				tagless: "Keine Tags hinzugefügt",
				copy_json_data: "JSON-Daten in Zwischenablage kopiert",
				id_hint: "Das Ändern der Textur-ID kann alles kaputt machen",
				id: "Textur-ID",
				name: "Texturname",
				tags: "Textur-Typ",
			},
			uses: {
				title: "Verwendung(en)",
				singular: "Verwendung",
				plural: "Verwendung(en)",
				add_use: "Neue Verwendung hinzufügen",
				change_use: "Verwendung bearbeiten",
				add_edition_use: "Automatische %edition% Verwendung hinzufügen",
				no_use_found: "Keine Verwendungen für diese Textur gefunden",
				id_hint: "Das Ändern der Verwendungs-ID kann alles kaputt machen",
				id: "Verwendungs-ID",
				name: "Verwendungsname",
				edition: "Verwendungsedition",
			},
			paths: {
				title: "Dateipfad(e)",
				singular: "Dateipfad",
				plural: "Dateipfad(e)",
				add_path: "Neuen Dateipfad hinzufügen",
				change_path: "Dateipfad bearbeiten",
				no_path_found: "Keine Pfade für diese Verwendung gefunden",
				id_hint: "Das Ändern der Dateipfad-ID kann alles kaputt machen",
				id: "Dateipfad-ID",
				name_hint: "Der Pfad sollte im Stammverzeichnis beginnen (z. B. assets/…)",
				name_prefill: "Dies als Erstes eingeben, um die meisten Felder zu generieren!",
				name: "Dateipfad",
				versions: "Versionen",
				mcmeta: "Animiert",
			},
			merge_textures: {
				title: "Texturen zusammenführen",
				warning: "Dies wird die Quelltextur löschen und kann nicht rückgängig gemacht werden!",
				source: "Quelltextur-ID",
				destination: "Zieltextur-ID",
				invalid_id: "Ungültige Textur-ID",
			},
		},
		versions: {
			title: "Versionen",
			edition_filter: "Nach Edition filtern",
			version_result: "Versionsergebnisse",
			exists: "Versionsname ist bereits vorhanden",
			path_count_singular: "%d Pfad",
			path_count_plural: "%d Pfade",
			no_paths: "Keine zugehörigen Pfade",
			modal: {
				title: "Minecraft-Version bearbeiten",
				name: "Minecraft-Versionsname",
				edition: "Minecraft-Edition",
				warning: "Bitte nicht vergessen, alle Github Branch Namen zu aktualisieren!",
			},
			add: {
				title: "Neue Minecraft-Version hinzufügen",
				success: "Version erfolgreich hinzugefügt",
				new_edition: "Edition, zu der die Version hinzugefügt werden soll",
				template_version: "Vorlagenversion",
				new_version: "Neuer Versionsname",
			},
			delete: {
				description: "Möchtest du die Version %VERSION% für %EDITION% Edition löschen?",
				no_affected_paths: "Es werden keine Pfade betroffen sein",
				affected_paths_singular: "%d Pfad wird betroffen sein.",
				affected_paths_plural: "%d Pfade wird betroffen sein.",
			},
		},
		packs: {
			title: "Packs",
			tag_filter: "Texturtyp auswählen",
			pack_result: "Pack Ergebnisse",
			modal: {
				add_pack: "Neues Pack hinzufügen",
				change_pack: "Pack bearbeiten",
				id: "Pack-ID",
				id_creation_hint:
					"Eine Pack-ID kann entweder manuell angegeben oder automatisch generiert werden",
				id_editing_hint: "Ändern einer Pack-ID kann alles kaputt machen!",
				name: "Pack Name",
				tags: "Pack-Tags",
				resolution: "Pack-Auflösung",
				color: "Pack-Farbe",
				logo: "Pack-Logo-URL",
				github: {
					title: "GitHub",
					title_hint:
						"Eine Edition kann leer gelassen werden, wenn sie noch nicht unterstützt wird",
					length_notice: "Mindestens ein GitHub Repository muss vorhanden sein",
					organization: "Organisation",
					repository: "Repository",
				},
			},
			submissions: {
				title: "Informationen zur Einsendung",
				add_submission: "Informationen zur Einsendung hinzufügen",
				edit_submission: "Informationen der Einsendung bearbeiten",
				reference_pack: "Referenz-Pack",
				reference_hint: "Pack zum Vergleichen in Einsendungs-Embeds",
				contributor_role: "Mitwirkenden Rollen-ID",
				time_to_results: "Zeit bis zum Ergebnis",
				time_hint: "Verzögerungen werden in Tagen gemessen",
				channels: {
					title: "Discord Kanäle",
					title_hint:
						"Aktiviere den Entwicklermodus und klicke mit der rechten Maustaste auf einen Kanal, um die Kanal-ID zu erhalten",
					submit: "Kanal zur Einsendung",
					results: "Kanal für Ergebnisse",
				},
				ask_submission_deletion: "Sollen die Einsendungsinformationen für %s gelöscht werden (%d)?",
			},
		},
		settings: {
			title: "Globale Einstellungen bearbeiten",
		},
	},
};
